# Generated by Django 3.0.8 on 2020-08-01 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelname', models.CharField(max_length=30)),
                ('channelpicture', models.ImageField(default='../static/black.png', upload_to='')),
                ('date_created', models.CharField(default=datetime.date(2020, 8, 1), max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=100)),
                ('recording', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('subtitles', models.FileField(blank=True, upload_to='subtitles/')),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Not mentioned', '----choose category----'), ('films and animation', 'Film and animation'), ('cars and vehicles', 'Cars and Vehicles'), ('music', 'Music'), ('pets and animals', 'Pets and animals'), ('sports', 'Sports'), ('travel and events', 'Travel and events'), ('gaming', 'Gaming'), ('people and blogs', 'People and blogs'), ('comedy', 'Comedy'), ('entertainment', 'Entertainment'), ('news and politics', 'News and politics'), ('how-to and style', 'How-to and style'), ('education', 'Education'), ('science and technology', 'Science and Technology'), ('non-profit and activism', 'Non-profit and activism')], max_length=35)),
                ('published_date', models.CharField(default=datetime.date(2020, 8, 1), max_length=15)),
                ('views', models.IntegerField(default=0)),
                ('hideComments', models.BooleanField(default=False)),
                ('uploadedchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ytusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='WatchLateer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlater', to='videos.ytusers')),
                ('videos', models.ManyToManyField(blank=True, related_name='watchlatervideos', to='videos.Video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='watchHistory',
            field=models.ManyToManyField(blank=True, related_name='watchedVideos', to='videos.ytusers'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistname', models.CharField(max_length=30)),
                ('public', models.BooleanField(default=True)),
                ('channelname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelplaylists', to='videos.Channel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='videos.ytusers')),
                ('videoname', models.ManyToManyField(blank=True, related_name='playlistvideos', to='videos.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.CharField(default=datetime.date(2020, 8, 1), max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to='videos.ytusers')),
                ('videoname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='videos.Video')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchannels', to='videos.ytusers'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='videos.ytusers'),
        ),
    ]
