# Generated by Django 3.0.8 on 2020-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_channel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='fblink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='channel',
            name='instalink',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='channel',
            name='twitterlink',
            field=models.CharField(default='', max_length=500),
        ),
    ]
