# Generated by Django 3.0.8 on 2020-08-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20200805_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channelpicture',
            field=models.ImageField(blank=True, default='../static/black.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='coverpic',
            field=models.ImageField(blank=True, default='../static/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='fblink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='instalink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='twitterlink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
