# Generated by Django 3.0.8 on 2020-08-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20200810_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytusers',
            name='userpicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
