# Generated by Django 3.0.8 on 2020-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_ytusers_userpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytusers',
            name='userpicture',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
