# Generated by Django 3.0.8 on 2020-08-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20200812_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='likes',
            new_name='dislikes',
        ),
    ]
