# Generated by Django 3.0.8 on 2020-08-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_auto_20200823_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='channelname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='channelplaylists', to='videos.Channel'),
        ),
    ]
