# Generated by Django 3.0.8 on 2020-08-22 20:06

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField 


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_auto_20200823_0035'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='video',
            name='watchHistory',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='watchedVideos', to='videos.ytusers'),
        ),
    ]
