# Generated by Django 3.0.8 on 2020-08-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20200823_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='date_created',
            field=models.CharField(default=datetime.date(2020, 8, 26), max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(default=datetime.date(2020, 8, 26), max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_date',
            field=models.CharField(default=datetime.date(2020, 8, 26), max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles',
            field=models.FileField(blank=True, default='', upload_to='subtitles/'),
        ),
    ]
